"""Initial tables

Revision ID: 38909443bc1a
Revises: 
Create Date: 2025-07-10 13:57:01.945508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38909443bc1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('law_type', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('law_number', sa.String(), nullable=True),
    sa.Column('gazette_number', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('detail_url', sa.String(), nullable=False),
    sa.Column('pdf_downloaded', sa.Boolean(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('unprocessed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('act_id')
    )
    op.create_table('law_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['laws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relation_type', name='uq_relation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_relations')
    op.drop_table('laws')
    # ### end Alembic commands ###
