"""Added pdf_text

Revision ID: 55bd142480d1
Revises: 38909443bc1a
Create Date: 2025-07-10 14:42:05.927120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bd142480d1'
down_revision: Union[str, None] = '38909443bc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laws', sa.Column('pdf_text', sa.Text(), nullable=True))
    op.add_column('laws', sa.Column('pdf_text_extracted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laws', 'pdf_text_extracted_at')
    op.drop_column('laws', 'pdf_text')
    # ### end Alembic commands ###
